# site properties and page defaults
title: INSPIRE Lab
subtitle: "Transforming Information Retrieval with Cutting-Edge Research"
description: Welcome to the Intelligent Systems for Predictive Information Retrieval and Data Modeling (INSPIRE) Lab at Wilfrid Laurier University, Canada. We specialize in advancing the fields of natural language processing (NLP), machine learning, and large language models. Our research aims to enhance the accuracy, efficiency, and relevance of information retrieval systems through innovative algorithms and data modeling techniques. From semantic search to bias mitigation in recommender systems, our lab is dedicated to solving real-world challenges with interdisciplinary collaboration. Join us in pioneering the future of intelligent, adaptive, and user-centric information systems.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: jzhao@wlu.ca
  orcid: 0000-0001-9770-7616
  google-scholar: 9vsMVz8AAAAJ
  github: inspire-research
  # twitter: inspire-research
  # youtube: inspire-research

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
